#--------------------------------------------------------
# AWStats-Theme-Regulex
# 项目地址：https://github.com/lete114/AWStats-Theme-Regulex
# 演示地址：https://www.imlete.cn/
# 一个静态个人主页
#--------------------------------------------------------


# language 语言
language: zh-CN
author: Lete乐特 # author 名称
favicon: https://www.imlete.cn/img/favicon.ico # favicon 图标
description: JavaScript 正则表达式可视化工具 | JavaScript Regular Expression Visualizer # description 网站描述
keywords: Lete乐特,Lete,lete,lete114,Lete114,Regulex #关键字


# 自定义引入外部css、js
import:
  head: # 引入到</head>之前
    -
  top: # 引入到<body>之后
    -
  bottom: # 引入到</body>之前
    -
  # 例如：
  # - <link rel="stylesheet" href="/css/main.css">
  # - '<style>body{color: red}</style>' ## 注意由于css的‘{}’是关键符号所以需要(单/双)引号''
  # - <script>alert(1)</script>

# 分析(统计)
analytics:
  baidu:  # 百度分析
  google: # 谷歌分析


CDN:
  mainJs: /js/main.js
  mainCss: /css/main.css
  regulex: https://cdn.jsdelivr.net/npm/regulex/dist/regulex.js
